### ISSUE TITLE
KLapse Support

### ISSUE THREAD

**Issue by h4waii** [mTresk/android_kernel_oneplus_msm8998#1]
Are there any plans to include [KLapse](https://github.com/tanish2k09/KLapse-Livedisplay) support in this kernel?

It's a great new driver for adjusting display temperature directly in the kernel based on different settings, which are much more adjustable than AOSP, Omni, and LineageOS offer.

**Comment by mTresk** [comment]
Nope

**Comment by h4waii** [comment]
Would you accept a PR for this or you'd prefer to not include it at all?
